#!groovy some to remove
import com.gumtree.jenkins.*

projectName = 'madgex-advert-importer'

projectDir = projectName
projectRepoURL = "git@github.corp.ebay.com:gumtree/${projectName}.git"
projectBranch = "${env.BRANCH_NAME}"

// serviceName = "${env.SERVICE_NAME}"
serviceName = 'madgex-advert-importer' // to avoid accidentally overwritting image that works with ES 1.7

envToDeploy = "${env.ENV_TO_DEPLOY}".replace("gt-", "")

node {
    currentBuild.displayName = "#" + currentBuild.id + "-" + projectBranch

    sh "rm -rf ${projectDir}"

    withRepoScript(projectDir, projectRepoURL, projectBranch, "pipeline/common.groovy") { script ->

        env.MECHANIKER_REVISION = mechaniker.computeRevision(env.BRANCH_NAME)
        env.FULL_DOCKER_PATH = "dock.es.ecg.tools/gtuk/${serviceName}:${env.MECHANIKER_REVISION}"
        env.ORG = "gumtree"
        env.REPO_NAME = projectName
        env.PACKAGE_NAME = serviceName
        env.MECHANIKER_MANIFEST = mechaniker.readManifest("config/mechaniker/" + serviceName + "/application.yml")

        try {
            script.buildStage()

            script.buildDocker()

            script.testStage(serviceName, envToDeploy)

            script.releaseStage(projectBranch, envToDeploy)
        } finally {
            step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml,**/target/scalatest-reports/TEST-*.xml', allowEmptyResults: true])
        }
    }
}
